### ISSUE TITLE
MQTT error with 

### ISSUE THREAD

**Issue by xorguy** [grzegorz914/homebridge-enphase-envoy#128]
Hi.

MQTT fails with 7.11.15 and 7.11.16, latest working version was 7.11.14.

`Error: Unhandled error. ('MQTT Connect error: ReferenceError: MQTT is not defined')
    at MQTTCLIENT.emit (node:events:507:17)
    at MQTTCLIENT.connect (/homebridge/node_modules/homebridge-enphase-envoy/src/mqtt.js:35:18)
    at new MQTTCLIENT (/homebridge/node_modules/homebridge-enphase-envoy/src/mqtt.js:17:14)
    at new EnvoyDevice (/homebridge/node_modules/homebridge-enphase-envoy/src/envoydevice.js:396:25)
    at HomebridgeAPI.<anonymous> (/homebridge/node_modules/homebridge-enphase-envoy/index.js:54:29)
    at HomebridgeAPI.emit (node:events:518:28)
    at HomebridgeAPI.signalFinished (/homebridge/node_modules/homebridge/src/api.ts:275:10)
    at ChildBridgeFork.startBridge (/homebridge/node_modules/homebridge/src/childBridgeFork.ts:189:14)`

**Comment by grzegorz914** [comment]
Fixed

**Comment by 0berkampf** [comment]
Hi,

It’s not fixed on my side, no more errors but messages are not published with the last version 7.11.17.
Thx for your help.

**Comment by grzegorz914** [comment]
sorry for this mistake, now is fixed

**Comment by 0berkampf** [comment]
Don’s be sorry, you’re doing a great job here!
Thx it’s working fine now.
